export const projects = [
  {
    client: "Mike Martin Media",
    project: "Website",
    description: "Mike Martin Media is a multi media production company. MMM is baed in St. Louis, MO, but they work all around the world. They needed a website that A website for a media company. A website for a rock band. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Donec nec nisl nec nisl. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Donec nec nisl nec nisl. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Donec nec nisl nec nisl. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Donec nec nisl nec nisl.",
    features: [
      "Responsive",
      "Accessible",
      "Analytics",
      "Tag Manager",
      "Cookie Consent",
      "Embedded Video",
      "Video Galleries",
      "Photo Galleries",
      "Blog",
      "Contact Form",
      "Instagram Feed",
    ],
    mobile_images: [
      "/images/projects/mmm/mmm-mobile.jpg",
      "/images/projects/mmm/mmm-mobile-2.jpg",
      "/images/projects/mmm/mmm-mobile-3.jpg",
      "/images/projects/mmm/mmm-mobile-4.jpg",
    ],
    desktop_image: [
      "/images/projects/mmm/mmm-desktop.png",
      "/images/projects/mmm/mmm-desktop-2.png",
      "/images/projects/mmm/mmm-desktop-3.png",
      "/images/projects/mmm/mmm-desktop-4.jpg",
    ],
    url: "mikemartinmedia.com",
  },
  {
    client: "The Long Emergency",
    project: "Website",
    description: "Mike Martin Media is a multi media production company. MMM is baed in St. Louis, MO, but they work all around the world. They needed a website that A website for a media company. A website for a rock band. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Donec nec nisl nec nisl. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Donec nec nisl nec nisl. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Donec nec nisl nec nisl. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ut purus eget nunc. Donec nec nisl nec nisl.",
    mobile_images: [
      "/images/projects/the-long-emergency/the-long-emergency-mobile.jpg",
      "/images/projects/the-long-emergency/the-long-emergency-mobile.jpg",
      "/images/projects/the-long-emergency/the-long-emergency-mobile.jpg",
      "/images/projects/the-long-emergency/the-long-emergency-mobile.jpg",
    ],
    desktop_image: [
      "/images/projects/the-long-emergency/the-long-emergency-desktop.png",
      "/images/projects/the-long-emergency/the-long-emergency-desktop.png",
      "/images/projects/the-long-emergency/the-long-emergency-desktop.png",
      "/images/projects/the-long-emergency/the-long-emergency-desktop.png",
    ],
    url: "thelongemergency.net",
    features: [
      "Responsive",
      "Accessible",
      "Analytics",
      "Gig Calendar",
      "Audio Player",
      "Audio Downloads",
      // "Merch Store",
      "Blog",
      "Contact Form",
      // "Photo Gallery",
      // "Video Gallery",
      // "Mailing List",
    ],
  },
]