export const projects = [
  {
    client: "Mike Martin Media",
    project: "Website",
    description: "Mike Martin Media is an multi media production company based in St Louis, Missouri and working all around the world. When I first began working with MMM they had an old WordPress website that was not meeting their needs. Our first order of business was to stabilize the old website. After that I worked with them to design and develop a new website, custom made to fit their specific needs. The biggest challenge was working with a large amount of video content. They needed a website to showcase their work for potential clients. Video files are big and not always easy to work with. I was able to optimize the website to load quickly and display the video content in a way that was easy to navigate and view. Like all of our work, the website is fully responsive and looks great on any device. It features a blog, contact form, and an embedded Instagram feed. The website is also integrated with Google Analytics and Google Tag Manager for running ads and monitoring site traffic.",
    features: [
      "Responsive",
      "Analytics",
      "Tag Manager",
      "Cookie Consent",
      "Embedded Video",
      "Video Galleries",
      "Photo Galleries",
      "Blog",
      "Contact Form",
      "Instagram Feed",
      "Embedded Map",
    ],
    mobile_images: [
      "/images/projects/mmm/mobile/home-vid.mp4",
      "/images/projects/mmm/mobile/mmm-mobile.jpg",
      "/images/projects/mmm/mobile/mmm-mobile-2.jpg",
      "/images/projects/mmm/mobile/mmm-mobile-3.jpg",
      "/images/projects/mmm/mobile/mmm-mobile-4.jpg",
    ],
    desktop_image: [
      "/images/projects/mmm/desktop/mmm-desktop.png",
      "/images/projects/mmm/desktop/mmm-desktop-2.png",
      "/images/projects/mmm/desktop/mmm-desktop-3.png",
      "/images/projects/mmm/desktop/mmm-desktop-4.jpg",
      "/images/projects/mmm/desktop/livestream-desktop.png",
      "/images/projects/mmm/desktop/drone-desktop.png",
    ],
    url: "mikemartinmedia.com",
  },
  {
    client: "The Long Emergency",
    project: "Website",
    description: "The Long Emergency is a rock band in St. Louis, Missouri. They needed a website to showcase their music, shows, and merchandise. The website features a gig calendar, music player, audio downloads, merch store, blog, and contact form. The website is fully responsive and accessible. It is integrated with Vercel Analytics for monitoring site traffic. The website is built with Next.js and Tailwind CSS. Not all features are currently live. The band is gearing up for a return to performing after an extended hiatus. The website will be updated with new content and features as the band gets back to playing shows and releasing new music.",
    mobile_images: [
      "/images/projects/the-long-emergency/mobile/landing.jpg",
      "/images/projects/the-long-emergency/mobile/merch.jpg",
      "/images/projects/the-long-emergency/mobile/menu.jpg",
      "/images/projects/the-long-emergency/mobile/music.jpg",
      "/images/projects/the-long-emergency/mobile/shows.jpg",
      "/images/projects/the-long-emergency/mobile/music-player-sing-me-to-sleep.jpg",
    ],
    desktop_image: [
      "/images/projects/the-long-emergency/desktop/desktop.png",
      "/images/projects/the-long-emergency/desktop/about-desktop.png",
      "/images/projects/the-long-emergency/desktop/music-desktop.png",
      "/images/projects/the-long-emergency/desktop/shows-desktop.png",
      "/images/projects/the-long-emergency/desktop/merch-desktop.png",
      "/images/projects/the-long-emergency/desktop/contact-desktop.png",
    ],
    url: "thelongemergency.net",
    features: [
      "Responsive",
      "Analytics",
      "Gig Calendar",
      "Audio Player",
      "Audio Downloads",
      "Merch Store",
      "Blog",
      "Contact Form",
      "Mailing List",
    ],
  },
  {
    client: "Vain Mainstream",
    project: "Website",
    description: "Vain Mainstream is an indie rock musician based in Minneapolis, Minnesota, best known for his work with the legendary Twin Cities garage rock orchestra, \"The Drug Budget\". From December of 2022 through the summer of 2023 Vain Mainstream undertook an ambitious project he called \"The Life Expectancy Tour\". The project took him all over the world, recording and performing an eclectic collection of cover songs performed with his own unique spin. I was hired to design and develop a website to document the project. As the tour progressed we updated the site each week with a new track. The website features an embedded audio player, audio downloads, and embedded videos. At the client's direction the site was designed to reflect an early internet aesthetic reminiscent. To achieve this I used pixelated graphics and a pixelated font along with a white background, blue links, and simple animations. As always the site is fully responsive. It is also an installable progressive web application.",
    mobile_images: [
      "/images/projects/vain-mainstream/mobile/radio-gif.gif",
      "/images/projects/vain-mainstream/mobile/radio.jpg",
      "/images/projects/vain-mainstream/mobile/radio-1.jpg",
      "/images/projects/vain-mainstream/mobile/audio.jpg",
      "/images/projects/vain-mainstream/mobile/video-1.jpg",
      "/images/projects/vain-mainstream/mobile/video-2.jpg",
      "/images/projects/vain-mainstream/mobile/video-3.jpg",
    ],
    desktop_image: [
      "/images/projects/vain-mainstream/desktop/radio.png",
      "/images/projects/vain-mainstream/desktop/audio.png",
      "/images/projects/vain-mainstream/desktop/video.png",
    ],
    url: "vainmainstream.com",
    features: [
      "Responsive",
      "Embedded Videos",
      "Audio Player",
      "Audio Downloads",
      "Animation"
    ],
  },
]