export const projects = [
  {
    client: "Mike Martin Media",
    project: "Website",
    description: "Mike Martin Media is an multi media production company based in St Louis , Missouri and working all around the world. When I first began working with MMM they had an old WordPress website that was not meeting their needs. Our first order of business was to stabilize the old website. After that I worked with them to design and develop a new website custom made to fit their specific needs. The biggest challenge was working with a large amount of video content. They needed a website to showcase their work for potential clients. Video files are big and not always easy to work with. I was able to optimize the website to load quickly and display the video content in a way that was easy to navigate and view. The website is fully responsive and accessible. It features a blog, contact form, and an embedded Instagram feed. The website is also integrated with Google Analytics and Google Tag Manager for running ads and monitoring site traffic.",
    features: [
      "Responsive",
      "Accessible",
      "Analytics",
      "Tag Manager",
      "Cookie Consent",
      "Embedded Video",
      "Video Galleries",
      "Photo Galleries",
      "Blog",
      "Contact Form",
      "Instagram Feed",
      "Embedded Map",
    ],
    mobile_images: [
      "/images/projects/mmm/mobile/mmm-mobile.jpg",
      "/images/projects/mmm/mobile/mmm-mobile-2.jpg",
      "/images/projects/mmm/mobile/mmm-mobile-3.jpg",
      "/images/projects/mmm/mobile/mmm-mobile-4.jpg",
    ],
    desktop_image: [
      "/images/projects/mmm/desktop/mmm-desktop.png",
      "/images/projects/mmm/desktop/mmm-desktop-2.png",
      "/images/projects/mmm/desktop/mmm-desktop-3.png",
      "/images/projects/mmm/desktop/mmm-desktop-4.jpg",
      "/images/projects/mmm/desktop/livestream-desktop.png",
      "/images/projects/mmm/desktop/drone-desktop.png",
    ],
    url: "mikemartinmedia.com",
  },
  {
    client: "The Long Emergency",
    project: "Website",
    description: "The Long Emergency is a band in St. Louis, Missouri. They needed a website to showcase their music, shows, and merchandise. The website features a gig calendar, music player, audio downloads, merch store, blog, and contact form. The website is fully responsive and accessible. It is integrated with Vercel Analytics for monitoring site traffic. The website is built with Next.js and Tailwind CSS. Not all features are curretnly live. The band is gearing up for a return to performing after an extended hiatus. The website will be updated with new content and features as the band gets back to playing shows.",
    mobile_images: [
      "/images/projects/the-long-emergency/mobile/landing.jpg",
      "/images/projects/the-long-emergency/mobile/merch.jpg",
      "/images/projects/the-long-emergency/mobile/menu.jpg",
      "/images/projects/the-long-emergency/mobile/music.jpg",
      "/images/projects/the-long-emergency/mobile/shows.jpg",
      "/images/projects/the-long-emergency/mobile/music-player-sing-me-to-sleep.jpg",
      // "/images/projects/the-long-emergency/mobile/.jpg",
    ],
    desktop_image: [
      "/images/projects/the-long-emergency/desktop/desktop.png",
      "/images/projects/the-long-emergency/desktop/about-desktop.png",
      "/images/projects/the-long-emergency/desktop/music-desktop.png",
      "/images/projects/the-long-emergency/desktop/shows-desktop.png",
      "/images/projects/the-long-emergency/desktop/merch-desktop.png",
      "/images/projects/the-long-emergency/desktop/contact-desktop.png",
    ],
    url: "thelongemergency.net",
    features: [
      "Responsive",
      "Accessible",
      "Analytics",
      "Gig Calendar",
      "Audio Player",
      "Audio Downloads",
      "Merch Store",
      "Blog",
      "Contact Form",
      // "Photo Gallery",
      // "Video Gallery",
      "Mailing List",
    ],
  },
  {
    client: "Vain Mainstream",
    project: "Website",
    description: "Vain Mainstream is an indie rock musician based in Minneapolis, Minnesota.",
    mobile_images: [
      "/images/projects/vain-mainstream/mobile/radio-gif.gif",
      "/images/projects/vain-mainstream/mobile/radio.jpg",
      "/images/projects/vain-mainstream/mobile/radio-1.jpg",
      "/images/projects/vain-mainstream/mobile/audio.jpg",
      "/images/projects/vain-mainstream/mobile/video.jpg",
      "/images/projects/vain-mainstream/mobile/video-1.jpg",
      "/images/projects/vain-mainstream/mobile/video-2.jpg",
      "/images/projects/vain-mainstream/mobile/video-3.jpg",
    ],
    desktop_image: [
      "/images/projects/vain-mainstream/desktop/radio.png",
      "/images/projects/vain-mainstream/desktop/audio.png",
      "/images/projects/vain-mainstream/desktop/video.png",
    ],
    url: "vainmainstream.com",
    features: [
      "Responsive",
      "Accessible",
      "Embedded Videos",
      "Audio Player",
      "Audio Downloads",
      "Animation"
    ],
  },
]