import { BiLogoPhp } from "react-icons/bi";
import { text } from "stream/consumers";

export const themes = {
  funk: {
    avif: "/images/backgrounds/funk.avif",
    webp: "/images/backgrounds/funk.webp",
    alt: "Funky abstract background with vibrant colors and dynamic shapes",
    color: "black",
    // textShadow: "text-shadow-white-background-black",
    // logoShadow: "logo-shadow-white",
    bgColor: "bg-black",
    textOpposite: "text-white",
    bgOpposite: "bg-white",
    logoInvert: "",
  },
  blues: {
    avif: "/images/backgrounds/blues.avif",
    webp: "/images/backgrounds/blues.webp",
    alt: "Cool blue abstract background with smooth gradients and flowing lines",
    color: "white",
    // textShadow: "text-shadow-black-background-black",
    // logoShadow: "logo-shadow-black",
    bgColor: "bg-white",
    textOpposite: "text-black",
    bgOpposite: "bg-black",
    logoInvert: "invert",
  },
  rock: {
    avif: "/images/backgrounds/rock.avif",
    webp: "/images/backgrounds/rock.webp",
    alt: "Bold rock-inspired background with strong contrasts and dynamic shapes",
    color: "black",
    // textShadow: "text-shadow-white-background-black",
    // logoShadow: "logo-shadow-white",
    bgColor: "bg-black",
    textOpposite: "text-white",
    bgOpposite: "bg-white",
    logoInvert: "",
  },
  jazz: {
    avif: "/images/backgrounds/jazz.avif",
    webp: "/images/backgrounds/jazz.webp",
    alt: "Smooth jazz-inspired background with rich colors and elegant curves",
    color: "white",
    // textShadow: "text-shadow-black-background-black",
    // logoShadow: "logo-shadow-black",
    bgColor: "bg-white",
    textOpposite: "text-black",
    bgOpposite: "bg-black",
    logoInvert: "invert",
  },
};
